export const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAIL = 'GET_ADDRESS_FAIL'

export const CREATE_MY_ADDRESS_SUCCESS = 'CREATE_MY_ADDRESS_SUCCESS'
export const CREATE_MY_ADDRESS_REQUEST = 'CREATE_MY_ADDRESS_REQUEST'
export const CREATE_MY_ADDRESS_FAIL = 'CREATE_MY_ADDRESS_FAIL'
export const CREATE_MY_ADDRESS_RESET = 'CREATE_MY_ADDRESS_RESET'