export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL'
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL'

export const OPEN_ADDRESS_MODAL = 'OPEN_ADDRESS_MODAL'
export const CLOSE_ADDRESS_MODAL = 'CLOSE_ADDRESS_MODAL'